modLoader = "javafml"
loaderVersion = "[47,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "universal_dev_toolbox"
version = "1.0.0"
displayName = "Universal Dev Toolbox"
authors = "y271727uy"
description = '''通用开发工具箱'''

[[dependencies."universal_dev_toolbox"]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."universal_dev_toolbox"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"